#!/usr/bin/env node
/**
 * Single source of truth: root `VERSION` file.
 *
 * Syncs that version into:
 *   - package.json / package-lock.json
 *   - src-tauri/tauri.conf.json (Tauri + POINTER_APP_VERSION via build.rs)
 *   - Cargo.toml [workspace.package]
 *   - src/lib/appVersion.ts (frontend fallback)
 *
 * Usage:
 *   npm run version:sync          # write all targets from VERSION
 *   npm run version:sync -- --check   # exit 1 if any target drifts
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const VERSION_FILE = path.join(ROOT, 'VERSION')
const checkOnly = process.argv.includes('--check')

function readVersion() {
  const raw = fs.readFileSync(VERSION_FILE, 'utf8').trim()
  if (!/^\d+\.\d+\.\d+([.-][0-9A-Za-z.-]+)?$/.test(raw)) {
    throw new Error(`Invalid VERSION "${raw}" (expected semver like 0.1.2)`)
  }
  return raw
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'))
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`)
}

function replaceCargoWorkspaceVersion(toml, version) {
  if (/\[workspace\.package\][\s\S]*?^version\s*=/m.test(toml)) {
    return toml.replace(
      /(\[workspace\.package\][\s\S]*?^version\s*=\s*")[^"]+(")/m,
      `$1${version}$2`
    )
  }
  if (/^\[workspace\]/m.test(toml)) {
    return toml.replace(
      /^\[workspace\][^\n]*\n(?:[^\[]*\n)*/m,
      (block) => `${block.trimEnd()}\n\n[workspace.package]\nversion = "${version}"\n`
    )
  }
  throw new Error('Cargo.toml missing [workspace] table')
}

function syncPackageJson(version) {
  const filePath = path.join(ROOT, 'package.json')
  const pkg = readJson(filePath)
  const before = pkg.version
  pkg.version = version
  if (!checkOnly && before !== version) writeJson(filePath, pkg)
  return { file: 'package.json', before, after: version, ok: before === version }
}

function syncPackageLock(version) {
  const filePath = path.join(ROOT, 'package-lock.json')
  const lock = readJson(filePath)
  const before = lock.version
  lock.version = version
  if (lock.packages && lock.packages['']) {
    lock.packages[''].version = version
  }
  if (!checkOnly && before !== version) writeJson(filePath, lock)
  return { file: 'package-lock.json', before, after: version, ok: before === version }
}

function syncTauriConf(version) {
  const filePath = path.join(ROOT, 'src-tauri/tauri.conf.json')
  const conf = readJson(filePath)
  const before = conf.version
  conf.version = version
  if (!checkOnly && before !== version) writeJson(filePath, conf)
  return { file: 'src-tauri/tauri.conf.json', before, after: version, ok: before === version }
}

function syncCargoWorkspace(version) {
  const filePath = path.join(ROOT, 'Cargo.toml')
  const beforeRaw = fs.readFileSync(filePath, 'utf8')
  const m = beforeRaw.match(/\[workspace\.package\][\s\S]*?^version\s*=\s*"([^"]+)"/m)
  const before = m ? m[1] : '(missing)'
  const afterRaw = replaceCargoWorkspaceVersion(beforeRaw, version)
  if (!checkOnly && beforeRaw !== afterRaw) fs.writeFileSync(filePath, afterRaw)
  return { file: 'Cargo.toml [workspace.package]', before, after: version, ok: before === version }
}

function syncAppVersionTs(version) {
  const filePath = path.join(ROOT, 'src/lib/appVersion.ts')
  const next = `/** Generated by \`npm run version:sync\` from root VERSION. Do not edit. */\nexport const APP_VERSION = '${version}'\n`
  const before = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : ''
  const beforeMatch = before.match(/APP_VERSION = '([^']+)'/)
  const beforeVer = beforeMatch ? beforeMatch[1] : '(missing)'
  if (!checkOnly && before !== next) fs.writeFileSync(filePath, next)
  return { file: 'src/lib/appVersion.ts', before: beforeVer, after: version, ok: beforeVer === version }
}

function main() {
  const version = readVersion()
  const results = [
    syncPackageJson(version),
    syncPackageLock(version),
    syncTauriConf(version),
    syncCargoWorkspace(version),
    syncAppVersionTs(version),
  ]

  let drifted = false
  for (const r of results) {
    if (r.ok) {
      console.log(`[version] ok  ${r.file} = ${r.after}`)
    } else if (checkOnly) {
      drifted = true
      console.error(`[version] DRIFT ${r.file}: ${r.before} != ${r.after}`)
    } else {
      console.log(`[version] set ${r.file}: ${r.before} → ${r.after}`)
    }
  }

  if (checkOnly && drifted) {
    console.error('\nRun: npm run version:sync')
    process.exit(1)
  }
  console.log(`[version] ${checkOnly ? 'check passed' : 'synced'} VERSION=${version}`)
}

main()
